import { useEffect, useRef, useState } from "react";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { apiRequest } from "../../lib/apiClient";
import { EmptyState, ErrorState, LoadingState } from "../../components/ui/Feedback";
import { PageHeader } from "../../components/ui/PageHeader";
import { Panel } from "../../components/ui/Panel";

export function ConversationsPage(){const [selectedId,setSelectedId]=useState(null);const messagesEndRef=useRef(null);const client=useQueryClient();const list=useQuery({queryKey:["conversations"],queryFn:()=>apiRequest("/api/conversations")});const detail=useQuery({queryKey:["conversation",selectedId],queryFn:()=>apiRequest(`/api/conversations/${selectedId}`),enabled:Boolean(selectedId)});const action=useMutation({mutationFn:({id,path,body})=>apiRequest(`/api/conversations/${id}/${path}`,{method:"POST",body:body?JSON.stringify(body):undefined}),onSuccess:()=>{client.invalidateQueries({queryKey:["conversations"]});client.invalidateQueries({queryKey:["conversation",selectedId]});}});const selected=detail.data;
  useEffect(()=>{if(selected?.messages?.length)messagesEndRef.current?.scrollIntoView({block:"end"});},[selected?.messages?.length,selectedId]);
  if(list.isLoading)return <LoadingState/>;if(list.isError)return <ErrorState error={list.error}/>;
  function reply(event){event.preventDefault();const form=event.currentTarget;action.mutate({id:selectedId,path:"reply",body:{content:new FormData(form).get("content")}},{onSuccess:()=>form.reset()});}
  return <><PageHeader title="Conversations" description="Review customer context and step in when a human is needed."/><div className="conversation-layout"><Panel className="conversation-list" title="Inbox">{list.data.length?list.data.map(c=><button key={c.id} className={`conversation-row ${selectedId===c.id?"selected":""}`} onClick={()=>setSelectedId(c.id)}><span><strong>{c.external_customer_id}</strong><small>{c.channel} · {c.message_count} messages</small></span><span className={`status ${c.status}`}>{c.status.replaceAll("_"," ")}</span></button>):<EmptyState description="Customer conversations will appear here."/>}</Panel><Panel className="transcript" title={selected?selected.external_customer_id:"Conversation"} actions={selected&&<button className="button secondary small" disabled={action.isPending} onClick={()=>action.mutate({id:selected.id,path:selected.status==="handed_over"?"resume":"handover"})}>{selected.status==="handed_over"?"Resume AI":"Take over"}</button>}>{detail.isLoading&&<p className="muted">Loading conversation…</p>}{selected?<><div className="messages">{selected.messages.map(message=><article key={message.id} className={`message ${message.sender_type}`}><small>{message.sender_type}</small><p>{message.content}</p></article>)}<div ref={messagesEndRef}/></div>{selected.status==="handed_over"&&<form className="reply-form" onSubmit={reply}><input name="content" placeholder="Write a seller reply…" required/><button disabled={action.isPending}>Send</button></form>}</>:!detail.isLoading&&<EmptyState title="Select a conversation" description="Choose a customer from the inbox to see the transcript."/>}</Panel></div></>}
