import { useState } from "react";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { apiRequest } from "../../lib/apiClient";
import { DataTable } from "../../components/ui/DataTable";
import { ErrorState, LoadingState } from "../../components/ui/Feedback";
import { Modal } from "../../components/ui/Modal";
import { PageHeader } from "../../components/ui/PageHeader";
import { Panel } from "../../components/ui/Panel";

export function ProductsPage(){const [editing,setEditing]=useState(null);const [open,setOpen]=useState(false);const client=useQueryClient();const query=useQuery({queryKey:["products"],queryFn:()=>apiRequest("/api/products")});const save=useMutation({mutationFn:({id,payload})=>apiRequest(`/api/products${id?`/${id}`:""}`,{method:id?"PATCH":"POST",body:JSON.stringify({product:payload})}),onSuccess:()=>{client.invalidateQueries({queryKey:["products"]});setOpen(false);setEditing(null);}});if(query.isLoading)return <LoadingState/>;if(query.isError)return <ErrorState error={query.error}/>;
  const edit=p=>{setEditing(p);setOpen(true)};const columns=[{key:"name",label:"Product",render:r=><div><strong>{r.name}</strong><small>{r.description||"No description"}</small></div>},{key:"price",label:"Price",render:r=>`${r.price} BDT`},{key:"stock_quantity",label:"Stock"},{key:"active",label:"Visibility",render:r=><span className={`status ${r.active?"active":"cancelled"}`}>{r.active?"Active":"Inactive"}</span>},{key:"actions",label:"",render:r=><button className="button secondary small" onClick={()=>edit(r)}>Edit</button>}];
  function submit(event){event.preventDefault();const f=event.currentTarget;const v=Object.fromEntries(new FormData(f));save.mutate({id:editing?.id,payload:{...v,active:f.elements.active.checked}})}
  return <><PageHeader title="Products" description="The catalog and facts used during sales conversations." actions={<button onClick={()=>{setEditing(null);setOpen(true)}}>Add product</button>}/><Panel><DataTable columns={columns} rows={query.data} emptyMessage="Add a product to start taking orders."/></Panel><Modal title={editing?"Edit product":"Add product"} open={open} onClose={()=>{setOpen(false);setEditing(null)}}><form key={editing?.id||"new"} onSubmit={submit}><label>Product name<input name="name" defaultValue={editing?.name} required/></label><div className="form-grid"><label>Price<input name="price" type="number" min="0" step="0.01" defaultValue={editing?.price} required/></label><label>Stock quantity<input name="stock_quantity" type="number" min="0" defaultValue={editing?.stock_quantity} required/></label></div><label>Description<textarea name="description" defaultValue={editing?.description}/></label><label>Tags<input name="tags" defaultValue={editing?.tags}/></label><label className="checkbox"><input name="active" type="checkbox" defaultChecked={editing?.active??true}/>Visible to customers</label>{save.error&&<p className="form-error">{save.error.message}</p>}<div className="form-actions"><button type="button" className="button secondary" onClick={()=>setOpen(false)}>Cancel</button><button disabled={save.isPending}>{save.isPending?"Saving…":"Save product"}</button></div></form></Modal></>}
