import { useState } from "react";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { apiRequest } from "../../lib/apiClient";
import { DataTable } from "../../components/ui/DataTable";
import { ErrorState, LoadingState } from "../../components/ui/Feedback";
import { Modal } from "../../components/ui/Modal";
import { PageHeader } from "../../components/ui/PageHeader";
import { Panel } from "../../components/ui/Panel";

export function BusinessesPage(){const [open,setOpen]=useState(false);const client=useQueryClient();const query=useQuery({queryKey:["businesses"],queryFn:()=>apiRequest("/admin/businesses")});const create=useMutation({mutationFn:(payload)=>apiRequest("/admin/businesses",{method:"POST",body:JSON.stringify(payload)}),onSuccess:()=>{client.invalidateQueries({queryKey:["businesses"]});setOpen(false);}});if(query.isLoading)return <LoadingState/>;if(query.isError)return <ErrorState error={query.error}/>;
  const columns=[{key:"name",label:"Business",render:r=><div><strong>{r.name}</strong><small>{r.slug}</small></div>},{key:"category",label:"Category"},{key:"default_language",label:"Language"},{key:"status",label:"Status",render:r=><span className={`status ${r.status}`}>{r.status}</span>},{key:"created_at",label:"Created",render:r=>new Date(r.created_at).toLocaleDateString()}];
  function submit(event){event.preventDefault();const v=Object.fromEntries(new FormData(event.currentTarget));create.mutate({business:{name:v.name,slug:v.slug,category:v.category,default_language:v.default_language,timezone:"Asia/Dhaka",currency:"BDT"},owner:{name:v.owner_name,email:v.owner_email,password:v.owner_password}});}
  return <><PageHeader eyebrow="Platform administration" title="Businesses" description="Create and monitor isolated merchant workspaces." actions={<button onClick={()=>setOpen(true)}>Add business</button>}/><Panel><DataTable columns={columns} rows={query.data} emptyMessage="Create the first business workspace."/></Panel><Modal title="Create business" open={open} onClose={()=>setOpen(false)}><form onSubmit={submit}><div className="form-grid"><label>Business name<input name="name" required/></label><label>URL slug<input name="slug" pattern="[a-z0-9-]+" required/></label><label>Category<input name="category" required/></label><label>Default language<select name="default_language"><option value="banglish">Banglish</option><option value="english">English</option><option value="bengali">Bengali</option></select></label></div><h3>First owner</h3><div className="form-grid"><label>Name<input name="owner_name" required/></label><label>Email<input name="owner_email" type="email" required/></label><label className="full">Temporary password<input name="owner_password" type="password" minLength="12" required/></label></div>{create.error&&<p className="form-error">{create.error.message}</p>}<div className="form-actions"><button type="button" className="button secondary" onClick={()=>setOpen(false)}>Cancel</button><button disabled={create.isPending}>{create.isPending?"Creating…":"Create business"}</button></div></form></Modal></>;
}
